/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */

export default {
    'interface': {
        'en': {
            'arduinoEsp32S3.description': 'Integrates a dedicated AI accelerator and rich peripheral set for efficient, low-power IoT edge and AI workloads.'
        },
        'ru': {
            'arduinoEsp32S3.description': 'Интегрированный специализированный AI-ускоритель и богатый набор периферии для эффективной и энергоэкономичной работы на периферии IoT и задачах ИИ.'
        },
        'zh-cn': {
            'arduinoEsp32S3.description': '集成专用AI加速器和丰富的外设，适用于高效、低功耗的物联网边缘与AI工作负载。'
        },
        'zh-tw': {
            'arduinoEsp32S3.description': '整合專用AI加速器與豐富的周邊設備，適用於高效、低功耗的物聯網邊緣與AI工作負載。'
        }
    },
    'extensions': {
        'en': {
            'arduinoEsp32S3.modeMenu.input': 'input',
            'arduinoEsp32S3.modeMenu.output': 'output',
            'arduinoEsp32S3.modeMenu.inputPullup': 'input-pullup',
            'arduinoEsp32S3.modeMenu.inputPulldown': 'input-pulldown',
            'arduinoEsp32S3.levelMenu.high': 'high',
            'arduinoEsp32S3.levelMenu.low': 'low',
            'arduinoEsp32S3.InterrupModeMenu.risingEdge': 'rising edge',
            'arduinoEsp32S3.InterrupModeMenu.fallingEdge': 'falling edge',
            'arduinoEsp32S3.InterrupModeMenu.changeEdge': 'change edge',
            'arduinoEsp32S3.InterrupModeMenu.low': 'low level',
            'arduinoEsp32S3.InterrupModeMenu.high': 'high level',
            'arduinoEsp32S3.eolMenu.warp': 'warp',
            'arduinoEsp32S3.eolMenu.noWarp': 'no-warp',
            'arduinoEsp32S3.dataTypeMenu.integer': 'integer',
            'arduinoEsp32S3.dataTypeMenu.decimal': 'decimal',
            'arduinoEsp32S3.dataTypeMenu.string': 'string',
            'arduinoEsp32S3.category.pins': 'Pins',
            'arduinoEsp32S3.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'arduinoEsp32S3.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'arduinoEsp32S3.pins.setPwmOutput': 'set pwm pin [PIN] out [OUT]',
            'arduinoEsp32S3.pins.readDigitalPin': 'read digital pin [PIN]',
            'arduinoEsp32S3.pins.readAnalogPin': 'read analog pin [PIN]',
            'arduinoEsp32S3.pins.readTouchPin': 'read touch pin [PIN]',
            'arduinoEsp32S3.pins.setServoOutput': 'set servo pin [PIN] out [OUT]',
            'arduinoEsp32S3.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'arduinoEsp32S3.pins.detachInterrupt': 'detach interrupt pin [PIN]',
            'arduinoEsp32S3.category.serial': 'Serial',
            'arduinoEsp32S3.serial.multiSerialBegin': 'serial [NO] begin baudrate [VALUE]',
            'arduinoEsp32S3.serial.multiSerialPrint': 'serial [NO] print [VALUE] [EOL]',
            'arduinoEsp32S3.serial.multiSerialAvailable': 'serial [NO] available data length',
            'arduinoEsp32S3.serial.multiSerialReadAByte': 'serial [NO] read a byte',
            'arduinoEsp32S3.category.data': 'Data',
            'arduinoEsp32S3.data.dataMap': 'map [DATA] from ([ARG0], [ARG1]) to ([ARG2], [ARG3])',
            'arduinoEsp32S3.data.dataConstrain': 'constrain [DATA] between ([ARG0], [ARG1])',
            'arduinoEsp32S3.data.dataConvert': 'convert [DATA] to [TYPE]',
            'arduinoEsp32S3.data.dataConvertASCIICharacter': 'convert [DATA] to ASCII character',
            'arduinoEsp32S3.data.dataConvertASCIINumber': 'convert [DATA] to ASCII nubmer'
        },
        'ru': {
            'arduinoEsp32S3.modeMenu.input': 'ввод',
            'arduinoEsp32S3.modeMenu.output': 'вывод',
            'arduinoEsp32S3.modeMenu.inputPullup': 'ввод подтягивается к питанию',
            'arduinoEsp32S3.modeMenu.inputPulldown': 'ввод подтягивается к нулю',
            'arduinoEsp32S3.levelMenu.high': 'высокий',
            'arduinoEsp32S3.levelMenu.low': 'низкий',
            'arduinoEsp32S3.InterrupModeMenu.risingEdge': 'поднимающийся край',
            'arduinoEsp32S3.InterrupModeMenu.fallingEdge': 'падающий край',
            'arduinoEsp32S3.InterrupModeMenu.changeEdge': 'Изменить край',
            'arduinoEsp32S3.InterrupModeMenu.low': 'Низкий уровень',
            'arduinoEsp32S3.InterrupModeMenu.high': 'Высокий уровень',
            'arduinoEsp32S3.eolMenu.warp': 'перенос',
            'arduinoEsp32S3.eolMenu.noWarp': 'не переносить',
            'arduinoEsp32S3.dataTypeMenu.integer': 'целое',
            'arduinoEsp32S3.dataTypeMenu.decimal': 'десятичное',
            'arduinoEsp32S3.dataTypeMenu.string': 'строка',
            'arduinoEsp32S3.category.pins': 'Пины',
            'arduinoEsp32S3.pins.setPinMode': 'установить пин [PIN] в режим [MODE]',
            'arduinoEsp32S3.pins.setDigitalOutput': 'установить цифровой пин [PIN] на [LEVEL]',
            'arduinoEsp32S3.pins.setPwmOutput': 'установить ШИМ выход [PIN] в [OUT]',
            'arduinoEsp32S3.pins.readDigitalPin': 'читать цифровой пин [PIN]',
            'arduinoEsp32S3.pins.readAnalogPin': 'читать аналоговый вывод [PIN]',
            'arduinoEsp32S3.pins.readTouchPin': 'читать сенсорный пин [PIN]',
            'arduinoEsp32S3.pins.setServoOutput': 'установить серво пин [PIN] в [OUT]',
            'arduinoEsp32S3.pins.attachInterrupt': 'подключить прерывания на [PIN] в режиме [MODE] и выполнить',
            'arduinoEsp32S3.pins.detachInterrupt': 'отсоединить контакт прерывания [PIN]',
            'arduinoEsp32S3.category.serial': 'Последовательный порт',
            'arduinoEsp32S3.serial.multiSerialBegin': 'Последовательного порта [NO] начальная скорость [VALUE]',
            'arduinoEsp32S3.serial.multiSerialPrint': 'В последовательный порт  [NO] печатать [VALUE] [EOL]',
            'arduinoEsp32S3.serial.multiSerialAvailable': 'серийный [NO] доступная длина данных',
            'arduinoEsp32S3.serial.multiSerialReadAByte': 'Из последовательного порта [NO] прочитать байт',
            'arduinoEsp32S3.category.data': 'Данные',
            'arduinoEsp32S3.data.dataMap': 'сопоставить [DATA] с ([ARG0], [ARG1]) на ([ARG2], [ARG3])',
            'arduinoEsp32S3.data.dataConstrain': 'ограничить [DATA] между ([ARG0], [ARG1])',
            'arduinoEsp32S3.data.dataConvert': 'преобразовать [DATA] в [TYPE]',
            'arduinoEsp32S3.data.dataConvertASCIICharacter': 'преобразовать [DATA] в символ ASCII',
            'arduinoEsp32S3.data.dataConvertASCIINumber': 'преобразовать [DATA] в число ASCII'
        },
        'zh-cn': {
            'arduinoEsp32S3.modeMenu.input': '输入',
            'arduinoEsp32S3.modeMenu.output': '输出',
            'arduinoEsp32S3.modeMenu.inputPullup': '输入上拉',
            'arduinoEsp32S3.modeMenu.inputPulldown': '输入下拉',
            'arduinoEsp32S3.levelMenu.high': '高',
            'arduinoEsp32S3.levelMenu.low': '低电平',
            'arduinoEsp32S3.InterrupModeMenu.risingEdge': '上升沿',
            'arduinoEsp32S3.InterrupModeMenu.fallingEdge': '下降沿',
            'arduinoEsp32S3.InterrupModeMenu.changeEdge': '电平改变',
            'arduinoEsp32S3.InterrupModeMenu.low': '低电平',
            'arduinoEsp32S3.InterrupModeMenu.high': '高电平',
            'arduinoEsp32S3.eolMenu.warp': '换行',
            'arduinoEsp32S3.eolMenu.noWarp': '不换行',
            'arduinoEsp32S3.dataTypeMenu.integer': '整数',
            'arduinoEsp32S3.dataTypeMenu.decimal': '小数',
            'arduinoEsp32S3.dataTypeMenu.string': '字符串',
            'arduinoEsp32S3.category.pins': '引脚',
            'arduinoEsp32S3.pins.setPinMode': '设置引脚 [PIN] 模式 [MODE]',
            'arduinoEsp32S3.pins.setDigitalOutput': '设置引脚 [PIN] 输出 [LEVEL]',
            'arduinoEsp32S3.pins.setPwmOutput': '设置 PWM 引脚 [PIN] 输出 [OUT]',
            'arduinoEsp32S3.pins.readDigitalPin': '读取数字引脚 [PIN]',
            'arduinoEsp32S3.pins.readAnalogPin': '读取模拟引脚 [PIN]',
            'arduinoEsp32S3.pins.readTouchPin': '读取触摸引脚 [PIN]',
            'arduinoEsp32S3.pins.setServoOutput': '设置舵机引脚 [PIN] 输出 [OUT]',
            'arduinoEsp32S3.pins.attachInterrupt': '设置中断引脚 [PIN] 模式 [MODE] 执行',
            'arduinoEsp32S3.pins.detachInterrupt': '取消中断引脚 [PIN]',
            'arduinoEsp32S3.category.serial': '串口',
            'arduinoEsp32S3.serial.multiSerialBegin': '串口 [NO] 启动波特率  [VALUE]',
            'arduinoEsp32S3.serial.multiSerialPrint': '串口 [NO] 打印 [VALUE] [EOL]',
            'arduinoEsp32S3.serial.multiSerialAvailable': '串口 [NO] 可读取字节数',
            'arduinoEsp32S3.serial.multiSerialReadAByte': '串口 [NO] 读取1个字节',
            'arduinoEsp32S3.category.data': '数据',
            'arduinoEsp32S3.data.dataMap': '映射 [DATA] 从 ([ARG0], [ARG1]) 到 ([ARG2], [ARG3])',
            'arduinoEsp32S3.data.dataConstrain': '约束 [DATA] 介于 ([ARG0], [ARG1])',
            'arduinoEsp32S3.data.dataConvert': '转换 [DATA] 为 [TYPE]',
            'arduinoEsp32S3.data.dataConvertASCIICharacter': '转换 [DATA] 为 ASCII 字符',
            'arduinoEsp32S3.data.dataConvertASCIINumber': '转换 [DATA] 为 ASCII 编码'
        },
        'zh-tw': {
            'arduinoEsp32S3.modeMenu.input': '輸入',
            'arduinoEsp32S3.modeMenu.output': '輸出',
            'arduinoEsp32S3.modeMenu.inputPullup': '輸入上拉',
            'arduinoEsp32S3.modeMenu.inputPulldown': '輸入下拉',
            'arduinoEsp32S3.levelMenu.high': '高',
            'arduinoEsp32S3.levelMenu.low': '低',
            'arduinoEsp32S3.InterrupModeMenu.risingEdge': '上升沿',
            'arduinoEsp32S3.InterrupModeMenu.fallingEdge': '下降沿',
            'arduinoEsp32S3.InterrupModeMenu.changeEdge': '電位改變',
            'arduinoEsp32S3.InterrupModeMenu.low': '低電位',
            'arduinoEsp32S3.InterrupModeMenu.high': '高電位',
            'arduinoEsp32S3.eolMenu.warp': '換行',
            'arduinoEsp32S3.eolMenu.noWarp': '不換行',
            'arduinoEsp32S3.dataTypeMenu.integer': '整數',
            'arduinoEsp32S3.dataTypeMenu.decimal': '小數',
            'arduinoEsp32S3.dataTypeMenu.string': '字串',
            'arduinoEsp32S3.category.pins': '腳位',
            'arduinoEsp32S3.pins.setPinMode': '設置腳位 [PIN] 模式 [MODE]',
            'arduinoEsp32S3.pins.setDigitalOutput': '設置腳位 [PIN] 輸出 [LEVEL]',
            'arduinoEsp32S3.pins.setPwmOutput': '設置PWM腳位 [PIN] 輸出 [OUT]',
            'arduinoEsp32S3.pins.readDigitalPin': '讀取數字腳位 [PIN]',
            'arduinoEsp32S3.pins.readAnalogPin': '讀取類比腳位 [PIN]',
            'arduinoEsp32S3.pins.readTouchPin': '讀取觸摸腳位 [PIN]',
            'arduinoEsp32S3.pins.setServoOutput': '設置舵機腳位 [PIN] 輸出 [OUT]',
            'arduinoEsp32S3.pins.attachInterrupt': '設置中斷腳位 [PIN] 模式 [MODE] 執行',
            'arduinoEsp32S3.pins.detachInterrupt': '取消中斷腳位 [PIN]',
            'arduinoEsp32S3.category.serial': '串口',
            'arduinoEsp32S3.serial.multiSerialBegin': '串口 [NO] 啟動鮑率 [VALUE]',
            'arduinoEsp32S3.serial.multiSerialPrint': '串口 [NO] 列印 [VALUE] [EOL]',
            'arduinoEsp32S3.serial.multiSerialAvailable': '串口 [NO] 可讀取字節數',
            'arduinoEsp32S3.serial.multiSerialReadAByte': '串口 [NO] 讀取1個字節',
            'arduinoEsp32S3.category.data': '數據',
            'arduinoEsp32S3.data.dataMap': '映射 [DATA] 從 ([ARG0], [ARG1]) 到 ([ARG2], [ARG3])',
            'arduinoEsp32S3.data.dataConstrain': '約束 [DATA] 介於 ([ARG0], [ARG1])',
            'arduinoEsp32S3.data.dataConvert': '轉換 [DATA] 為 [TYPE]',
            'arduinoEsp32S3.data.dataConvertASCIICharacter': '轉換 [DATA] 為 ASCII 字符',
            'arduinoEsp32S3.data.dataConvertASCIINumber': '轉換 [DATA] 為 ASCII 編碼'
        }
    },
    'blocks': {
        'en': {},
        'ru': {},
        'zh-cn': {},
        'zh-tw': {}
    }
};
